const express = require('express');
const cors = require('cors');
const fetch = require('node-fetch');
const path = require('path');
const nodemailer = require('nodemailer');
const app = express();
app.use(cors({ origin: "*", methods: ["GET", "POST"], allowedHeaders: ["Content-Type"] }));
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
const RESTAURANT = {name:"Bella Tavola",cuisine:"Upscale Italian",city:"Elk Grove Village, IL",phone:"847-555-0192",notificationEmail:process.env.NOTIFICATION_EMAIL||"events@bellatavola.com",spaces:[{name:"The Rosario Room",capacity:80,type:"private"},{name:"The Garden Alcove",capacity:25,type:"semi-private"},{name:"Full Buyout",capacity:150,type:"buyout"}],menuItems:[{name:"Osso Buco",category:"entree",description:"Braised veal shank with gremolata and saffron risotto",popular:true,dietaryTags:[]},{name:"Branzino al Forno",category:"entree",description:"Whole roasted sea bass with lemon and herbs",popular:true,dietaryTags:["gluten-free"]},{name:"House-made Tagliatelle",category:"pasta",description:"Fresh pasta with slow-cooked Bolognese ragu",popular:true,dietaryTags:[]},{name:"Eggplant Parmigiana",category:"entree",description:"Classic baked eggplant with house marinara",popular:true,dietaryTags:["vegetarian"]},{name:"Chicken Marsala",category:"entree",description:"Pan-seared chicken with Marsala wine and mushrooms",popular:true,dietaryTags:[]},{name:"Tiramisu",category:"dessert",description:"Classic house-made tiramisu",popular:true,dietaryTags:["vegetarian"]}],wineList:[{name:"Chianti Classico",type:"red",region:"Tuscany",style:"medium-bodied, dry",pairsWith:["pasta","chicken","red sauce"],priceGlass:14,priceBottle:52},{name:"Montepulciano",type:"red",region:"Abruzzo",style:"medium-bodied, earthy",pairsWith:["braised meats","osso buco"],priceGlass:13,priceBottle:48},{name:"Barolo",type:"red",region:"Piedmont",style:"full-bodied",pairsWith:["osso buco","veal"],priceGlass:22,priceBottle:85},{name:"Pinot Grigio",type:"white",region:"Alto Adige",style:"light, crisp",pairsWith:["seafood","branzino"],priceGlass:13,priceBottle:46},{name:"Prosecco",type:"sparkling",region:"Veneto",style:"light, bubbly",pairsWith:["appetizers","celebrations"],priceGlass:12,priceBottle:44},{name:"Moscato d'Asti",type:"dessert",region:"Piedmont",style:"sweet, light",pairsWith:["tiramisu","desserts"],priceGlass:11,priceBottle:40}],todaysSpecials:[{name:"Rigatoni al Tartufo",description:"Rigatoni with black truffle cream sauce",mealPeriod:"dinner",price:28,active:true,soldOut:false},{name:"Branzino with Caponata",description:"Pan-seared branzino with Sicilian vegetable relish",mealPeriod:"dinner",price:34,active:true,soldOut:false}],cateringPackages:[{style:"Family-style",priceFrom:38,pricePer:"person"},{style:"Buffet",priceFrom:44,pricePer:"person"},{style:"Plated dinner",priceFrom:52,pricePer:"person"}],eventMinimum:500,depositPolicy:"25% deposit to hold your date",barOptions:["Full open bar","Beer and wine","Soft drinks only"],dietaryAccommodations:"Gluten-free, vegetarian, vegan accommodated with advance notice"};
const transcripts=new Map();
function buildSystemPrompt(r){const spaces=r.spaces.map(s=>`- ${s.name}: up to ${s.capacity} guests (${s.type})`).join('\n');const menu=r.menuItems.map(m=>`- ${m.name}: ${m.description}${m.dietaryTags.length?' | '+m.dietaryTags.join(', '):''}`).join('\n');const wines=r.wineList.map(w=>`- ${w.name} (${w.type}): ${w.style} | pairs with: ${w.pairsWith.join(', ')} | $${w.priceGlass}/glass`).join('\n');const specials=r.todaysSpecials.filter

cat > ~/Desktop/restaurantflow-voice/server.js << 'SERVEREOF'
const express = require('express');
const cors = require('cors');
const fetch = require('node-fetch');
const path = require('path');
const nodemailer = require('nodemailer');
const app = express();
app.use(cors({ origin: "*", methods: ["GET", "POST"], allowedHeaders: ["Content-Type"] }));
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
const RESTAURANT = {name:"Bella Tavola",cuisine:"Upscale Italian",city:"Elk Grove Village, IL",phone:"847-555-0192",notificationEmail:process.env.NOTIFICATION_EMAIL||"events@bellatavola.com",spaces:[{name:"The Rosario Room",capacity:80,type:"private"},{name:"The Garden Alcove",capacity:25,type:"semi-private"},{name:"Full Buyout",capacity:150,type:"buyout"}],menuItems:[{name:"Osso Buco",category:"entree",description:"Braised veal shank with gremolata and saffron risotto",popular:true,dietaryTags:[]},{name:"Branzino al Forno",category:"entree",description:"Whole roasted sea bass with lemon and herbs",popular:true,dietaryTags:["gluten-free"]},{name:"House-made Tagliatelle",category:"pasta",description:"Fresh pasta with slow-cooked Bolognese ragu",popular:true,dietaryTags:[]},{name:"Eggplant Parmigiana",category:"entree",description:"Classic baked eggplant with house marinara",popular:true,dietaryTags:["vegetarian"]},{name:"Chicken Marsala",category:"entree",description:"Pan-seared chicken with Marsala wine and mushrooms",popular:true,dietaryTags:[]},{name:"Tiramisu",category:"dessert",description:"Classic house-made tiramisu",popular:true,dietaryTags:["vegetarian"]}],wineList:[{name:"Chianti Classico",type:"red",region:"Tuscany",style:"medium-bodied, dry",pairsWith:["pasta","chicken","red sauce"],priceGlass:14,priceBottle:52},{name:"Montepulciano",type:"red",region:"Abruzzo",style:"medium-bodied, earthy",pairsWith:["braised meats","osso buco"],priceGlass:13,priceBottle:48},{name:"Barolo",type:"red",region:"Piedmont",style:"full-bodied",pairsWith:["osso buco","veal"],priceGlass:22,priceBottle:85},{name:"Pinot Grigio",type:"white",region:"Alto Adige",style:"light, crisp",pairsWith:["seafood","branzino"],priceGlass:13,priceBottle:46},{name:"Prosecco",type:"sparkling",region:"Veneto",style:"light, bubbly",pairsWith:["appetizers","celebrations"],priceGlass:12,priceBottle:44},{name:"Moscato d'Asti",type:"dessert",region:"Piedmont",style:"sweet, light",pairsWith:["tiramisu","desserts"],priceGlass:11,priceBottle:40}],todaysSpecials:[{name:"Rigatoni al Tartufo",description:"Rigatoni with black truffle cream sauce",mealPeriod:"dinner",price:28,active:true,soldOut:false},{name:"Branzino with Caponata",description:"Pan-seared branzino with Sicilian vegetable relish",mealPeriod:"dinner",price:34,active:true,soldOut:false}],cateringPackages:[{style:"Family-style",priceFrom:38,pricePer:"person"},{style:"Buffet",priceFrom:44,pricePer:"person"},{style:"Plated dinner",priceFrom:52,pricePer:"person"}],eventMinimum:500,depositPolicy:"25% deposit to hold your date",barOptions:["Full open bar","Beer and wine","Soft drinks only"],dietaryAccommodations:"Gluten-free, vegetarian, vegan accommodated with advance notice"};
const transcripts=new Map();
function buildSystemPrompt(r){const spaces=r.spaces.map(s=>`- ${s.name}: up to ${s.capacity} guests (${s.type})`).join('\n');const menu=r.menuItems.map(m=>`- ${m.name}: ${m.description}${m.dietaryTags.length?' | '+m.dietaryTags.join(', '):''}`).join('\n');const wines=r.wineList.map(w=>`- ${w.name} (${w.type}): ${w.style} | pairs with: ${w.pairsWith.join(', ')} | $${w.priceGlass}/glass`).join('\n');const specials=r.todaysSpecials.filter(s=>s.active&&!s.soldOut).map(s=>`- ${s.name} ($${s.price}): ${s.description}`).join('\n')||'- No specials loaded, tell customer to confirm with restaurant';const packages=r.cateringPackages.map(p=>`- ${p.style}: from $${p.priceFrom}/${p.pricePer}`).join('\n');return `You are Sofia, the AI concierge at ${r.name}, ${r.cuisine} in ${r.city}.\n\nSpeak warmly and naturally. Ask ONE question at a time. Keep replies 1-3 sentences. Acknowledge what customer said. Never sound like a form. Let customer say not sure. Sound like a real host.\n\nRESTAURANT INFO:\nPhone: ${r.phone}\nSpaces:\n${spaces}\nCatering:\n${packages}\nEvent minimum: $${r.eventMinimum} | Deposit: ${r.depositPolicy}\nBar: ${r.barOptions.join(' / ')}\nDietary: ${r.dietaryAccommodations}\n\nMENU:\n${menu}\n\nWINE LIST:\n${wines}\n\nTODAYS SPECIALS:\n${specials}\n\nPSYCHOLOGY:\n- Excited: match energy\n- Overwhelmed: slow down\n- Price-sensitive: note it gently\n- Frustrated: do not defend, apologize and escalate\n- Use social proof and soft commitment naturally\n\nGUARDRAILS:\n- Never guarantee availability\n- Never confirm exact pricing\n- Never guarantee allergy safety\n- Never confirm a booking\n- Never invent menu items or wine\n- If unsure say restaurant will confirm\n\nSERVICE RECOVERY: If customer mentions bad experience, switch modes. Do not defend. Collect facts. Escalate.\n\nWhen you have name, inquiry type, date, guest count if applicable, and contact info, wrap up warmly then output this JSON on its own line:\n\nINQUIRY_COMPLETE:{"inquiryType":"","customerName":"","phone":"","email":"","eventType":"","date":"","time":"","guestCount":"","privateRoom":"","foodStyle":"","barNeeds":"","dietaryNeeds":"","budgetConcern":"","urgency":"normal","notes":"","emotionalTone":"","guestIntent":"","revenueSignal":"","priceSensitivity":"","confidenceLevel":"","serviceRecoveryRisk":false,"recommendedManagerTone":"","managerNote":"","missingFields":[]}`;}
function generateManagerBrief(state,transcript,r){const urgency=state.urgency==='urgent'?'URGENT':state.urgency==='high'?'HOT':'NORMAL';const subject=`[${urgency}] ${state.inquiryType||'Inquiry'} - ${state.customerName||'Guest'} - ${state.date||'Date TBD'}`;const body=`RESTAURANTFLOW MANAGER BRIEF\n${r.name} - ${new Date().toLocaleString()}\n${state.serviceRecoveryRisk?'\nSERVICE RECOVERY RISK\n':''}\nCUSTOMER\nName: ${state.customerName||'Not provided'}\nPhone: ${state.phone||'Not provided'}\nEmail: ${state.email||'Not provided'}\n\nINQUIRY: ${state.inquiryType||'General'}\nEvent: ${state.eventType||'N/A'} | Date: ${state.date||'TBD'} | Guests: ${state.guestCount||'TBD'}\nFood: ${state.foodStyle||'TBD'} | Bar: ${state.barNeeds||'N/A'}\nDietary: ${state.dietaryNeeds||'None'} | Budget: ${state.budgetConcern||'Not discussed'}\n\nGUEST ASSESSMENT\nTone: ${state.emotionalTone||'Neutral'} | Intent: ${state.guestIntent||'Exploring'}\nRevenue: ${state.revenueSignal||'Unknown'} | Price sensitivity: ${state.priceSensitivity||'Unknown'}\nService recovery: ${state.serviceRecoveryRisk?'YES':'No'}\nManager tone: ${state.recommendedManagerTone||'Warm and professional'}\nNote: ${state.managerNote||'None'}\nMissing: ${state.missingFields?.length>0?state.missingFields.join(', '):'None'}\n\nSUGGESTED REPLY\nHi ${state.customerName||'there'}, thanks for reaching out to ${r.name}. We would love to help. I will follow up shortly.\n\nTRANSCRIPT\n${transcript||'Not available'}\n\nPowered by RestaurantFlow - NM Automation`;return{subject,body};}
async function sendManagerBrief(subject,body,r){if(!process.env.EMAIL_USER||!process.env.EMAIL_PASS){console.log('Email not configured. Subject:',subject);return;}const transporter=nodemailer.createTransport({service:'gmail',auth:{user:process.env.EMAIL_USER,pass:process.env.EMAIL_PASS}});await transporter.sendMail({from:process.env.EMAIL_USER,to:r.notificationEmail,subject,text:body});}
app.post('/api/chat',async(req,res)=>{const{messages,sessionId}=req.body;if(!messages)return res.status(400).json({error:'messages required'});if(!process.env.ANTHROPIC_API_KEY){console.error('ERROR: ANTHROPIC_API_KEY is not set');return res.status(500).json({error:'API key not configured'});}try{const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':process.env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:1200,system:buildSystemPrompt(RESTAURANT),messages})});if(!response.ok){const rawText=await response.text();console.error('Anthropic error:',response.status,rawText);let errMsg='API error';try{errMsg=JSON.parse(rawText).error?.message||errMsg;}catch(e){}return res.status(response.status).json({error:errMsg});}const data=await response.json();let reply=data.content?.[0]?.text||'';let inquiryState=null;let readyToSubmit=false;const match=reply.match(/INQUIRY_COMPLETE:(\{[\s\S]*?\})/);if(match){try{inquiryState=JSON.parse(match[1]);readyToSubmit=true;reply=reply.replace(/INQUIRY_COMPLETE:[\s\S]*$/,'').trim();}catch(e){console.error('Parse error:',e.message);}}if(sessionId){const existing=transcripts.get(sessionId)||[];const lastUser=messages[messages.length-1];existing.push('Guest: '+(lastUser?.content||''));existing.push('Sofia: '+reply);transcripts.set(sessionId,existing);}if(readyToSubmit&&inquiryState){const transcript=(transcripts.get(sessionId)||[]).join('\n');const{subject,body:briefBody}=generateManagerBrief(inquiryState,transcript,RESTAURANT);sendManagerBrief(subject,briefBody,RESTAURANT).catch(e=>console.error('Email error:',e.message));}let notificationPriority='normal';if(inquiryState?.serviceRecoveryRisk)notificationPriority='service_recovery';else if(inquiryState?.urgency==='urgent')notificationPriority='urgent';else if(inquiryState?.urgency==='high')notificationPriority='hot';res.json({reply,readyToSubmit,handoffNeeded:!!(inquiryState?.serviceRecoveryRisk||inquiryState?.urgency==='urgent'),notificationPriority,inquiryType:inquiryState?.inquiryType||null,emotionalTone:inquiryState?.emotionalTone||null,urgency:inquiryState?.urgency||null,revenueSignal:inquiryState?.revenueSignal||null,priceSensitivity:inquiryState?.priceSensitivity||null,serviceRecoveryRisk:inquiryState?.serviceRecoveryRisk||false,recommendedManagerTone:inquiryState?.recommendedManagerTone||null,managerNote:inquiryState?.managerNote||null,missingFields:inquiryState?.missingFields||[],state:inquiryState||null});}catch(err){console.error('Server error:',err.message);res.status(500).json({error:err.message});}});
app.get('/api/health',(req,res)=>{res.json({status:'ok',version:'4.0.0',restaurant:RESTAURANT.name,apiKeySet:!!process.env.ANTHROPIC_API_KEY});});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log('RestaurantFlow Voice running on port '+PORT));
